---
  - name: ELK Stack Config Playbook
    hosts: elk
    become: true
    tasks:

    - name: set vm.max_map_count to 262144 in sysctl
      sysctl: name={{ item.key }} value={{ item.value}}
      with_items:
        - { key: "vm.max_map_count", value: "262144" }

    - name: Install docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install docker python package
      pip:
         name: docker
         state: present

    - name: Install ELK container
      docker_container:
        name: elK
        image: sebp/elk:761
        state: started
        published_ports:
         - "5601:5601"
         - "9200:9200"
         - "5044:5044"
        restart_policy: always
